### ISSUE TITLE
Keynote Presentation: How an Extension Works

### ISSUE THREAD

**Issue by brianpattison** [nsfargo/NSFargo-iOS#2]
- [ ] An App Extension’s Life Cycle
  - viewDidAppear
  - viewWillDisappear
  - etc.
- [ ] How an App Extension Communicates
- [x] Some APIs Are Unavailable to App Extensions

**Comment by billburgess** [comment]
API's not available.
- Access a sharedApplication object, and so cannot use any of the methods on that object Use any API marked in header files with the NS_EXTENSION_UNAVAILABLE macro, or similar unavailability macro, or any API in an unavailable framework
- For example, in iOS 8.0, the HealthKit framework and EventKit UI framework are unavailable to app extensions.
- Access the camera or microphone on an iOS device
- Perform long-running background tasks
- The specifics of this limitation vary by platform, as described in the extension point chapters in this document.
  (An app extension can initiate uploads or downloads using an NSURLSession object, with results of those operations reported to the containing app.)
- Receive data using AirDrop
  (An app extension can send data using AirDrop in the same way an app does: by employing the UIActivityViewController class.)
